name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
#     - name: configure
#       run: ./configure

    - name: Install pyinstaller
      run: pip install pyinstaller
      
    - name: Install dependencies
      run: make
      
#     - name: Run check
#       run: make check
      
#     - name: Run distcheck
#       run: make distcheck
